#ifndef PAM_PRIVACYIDEA_PRIVACYIDEA_H
#define PAM_PRIVACYIDEA_PRIVACYIDEA_H

#include <string>
#include <map>
#include <security/pam_ext.h>
#include "response.h"
#include <nlohmann/json.hpp>
#include "fido_sign_response.h"
#include "offline_fido_credential.h"
// PAM_PRIVACYIDEA_VERSION and PAM_PRIVACYIDEA_USERAGENT are generated by CMake
// from include/version.h.in so they stay in sync with project(VERSION ...).
#include "version.h"

class PrivacyIDEA
{
public:
    PrivacyIDEA(pam_handle_t *pamh, std::string baseURL, std::string realm, bool sslVerify, std::string offlineFile, bool debug, long timeout, long offlineExpiryDays, std::string caCertPath = "", std::string rpId = "");

    ~PrivacyIDEA();

    int validateInitializePasskey(Response &response);

    int sendRequest(const std::string &url, const std::map<std::string, std::string> &parameters, const std::map<std::string, std::string> &headers,
                    std::string &response, bool postRequest = true);

    int parseResponse(const std::string &input, Response &out);

    int validateCheckFIDO(const FIDOSignResponse &signResponse, const std::string &transactionId, const std::string &origin, Response &response, const std::string &user = "");

    int offlineRefillFIDO(OfflineFIDOCredential &cred);

    // Parse the body of a /validate/offlinerefill response and apply any
    // resulting state changes to `cred`. Exposed for unit testing — production
    // code calls it via offlineRefillFIDO after the HTTP request.
    //
    // Return values:
    //   0   — response was OK or non-actionable (credential left intact)
    //   1   — malformed JSON
    //   905 — server signaled the credential should be deleted
    int parseOfflineRefillResponse(const std::string &body, OfflineFIDOCredential &cred);

    void refillAllOfflineCredentials();

    std::vector<OfflineFIDOCredential> findOfflineCredentialsForUser(const std::string &username) const;

    std::optional<OfflineFIDOCredential> findOfflineCredential(const std::string &serial) const;

    std::vector<OfflineFIDOCredential> getAllOfflineCredentials() const;

    void updateSignCount(const std::string &serial, uint32_t newSignCount);

private:
    pam_handle_t *pamh; // for syslog
    bool debug = false;

    std::string baseURL;
    bool sslVerify;
    std::string caCertPath;
    std::string realm;
    std::string configuredRpId; // for cross-checking server-supplied offline credentials
    long timeout = 0;
    long offlineExpirySeconds = 0; // Stored internally in seconds

    std::string offlineFile = "/etc/privacyidea/fido-offline-credentials.txt";
    nlohmann::json offlineJson;
    std::vector<OfflineFIDOCredential> offlineData;
    bool offlineDataDirty = false;

    std::string readAll(const std::string &file);
    OfflineFIDOCredential *_getMutableOfflineCredential(const std::string &serial);

    // Atomically write `content` to `file`: stages as `file.tmp` with mode
    // 0600, fsyncs, takes flock(LOCK_EX) only for the duration of the write
    // (not the whole PAM call — a stuck PIN prompt would otherwise block
    // every other concurrent auth), then renames over the target.
    bool writeAtomically(const std::string &file, const std::string &content);
};

#endif // PAM_PRIVACYIDEA_PRIVACYIDEA_H